ALTER TABLE KNOWLEDGES DROP COLUMN IF EXISTS NOTIFY_STATUS;
ALTER TABLE KNOWLEDGES ADD COLUMN NOTIFY_STATUS integer;
comment on column KNOWLEDGES.NOTIFY_STATUS is '騾夂衍繧ｹ繝・・繧ｿ繧ｹ';


ALTER TABLE KNOWLEDGE_FILES DROP COLUMN IF EXISTS DRAFT_ID;
ALTER TABLE KNOWLEDGE_FILES ADD COLUMN DRAFT_ID bigint;
comment on column KNOWLEDGE_FILES.DRAFT_ID is '荳区嶌縺巧D';


-- 繝翫Ξ繝・ず縺ｮ鬆・岼蛟､
drop table if exists DRAFT_ITEM_VALUES cascade;

create table DRAFT_ITEM_VALUES (
  DRAFT_ID bigint not null
  , TYPE_ID integer not null
  , ITEM_NO integer not null
  , ITEM_VALUE text
  , ITEM_STATUS integer not null
  , INSERT_USER integer
  , INSERT_DATETIME timestamp
  , UPDATE_USER integer
  , UPDATE_DATETIME timestamp
  , DELETE_FLAG integer
  , constraint DRAFT_ITEM_VALUES_PKC primary key (DRAFT_ID,TYPE_ID,ITEM_NO)
) ;

-- 繝翫Ξ繝・ず縺ｮ荳区嶌縺・
drop table if exists DRAFT_KNOWLEDGES cascade;

create table DRAFT_KNOWLEDGES (
  DRAFT_ID BIGINT GENERATED BY DEFAULT AS IDENTITY not null
  , KNOWLEDGE_ID bigint
  , TITLE character varying(1024) not null
  , CONTENT text
  , PUBLIC_FLAG integer
  , ACCESSES text
  , EDITORS text
  , TAG_NAMES text
  , TYPE_ID integer
  , INSERT_USER integer
  , INSERT_DATETIME timestamp
  , UPDATE_USER integer
  , UPDATE_DATETIME timestamp
  , DELETE_FLAG integer
  , constraint DRAFT_KNOWLEDGES_PKC primary key (DRAFT_ID)
) ;

comment on table DRAFT_ITEM_VALUES is '繝翫Ξ繝・ず縺ｮ鬆・岼蛟､';
comment on column DRAFT_ITEM_VALUES.DRAFT_ID is '荳区嶌縺巧D';
comment on column DRAFT_ITEM_VALUES.TYPE_ID is '繝・Φ繝励Ξ繝ｼ繝医・遞ｮ鬘曵D';
comment on column DRAFT_ITEM_VALUES.ITEM_NO is '鬆・岼NO';
comment on column DRAFT_ITEM_VALUES.ITEM_VALUE is '鬆・岼蛟､';
comment on column DRAFT_ITEM_VALUES.ITEM_STATUS is '繧ｹ繝・・繧ｿ繧ｹ';
comment on column DRAFT_ITEM_VALUES.INSERT_USER is '逋ｻ骭ｲ繝ｦ繝ｼ繧ｶ';
comment on column DRAFT_ITEM_VALUES.INSERT_DATETIME is '逋ｻ骭ｲ譌･譎・;
comment on column DRAFT_ITEM_VALUES.UPDATE_USER is '譖ｴ譁ｰ繝ｦ繝ｼ繧ｶ';
comment on column DRAFT_ITEM_VALUES.UPDATE_DATETIME is '譖ｴ譁ｰ譌･譎・;
comment on column DRAFT_ITEM_VALUES.DELETE_FLAG is '蜑企勁繝輔Λ繧ｰ';

comment on table DRAFT_KNOWLEDGES is '繝翫Ξ繝・ず縺ｮ荳区嶌縺・;
comment on column DRAFT_KNOWLEDGES.DRAFT_ID is '荳区嶌縺巧D';
comment on column DRAFT_KNOWLEDGES.KNOWLEDGE_ID is '繝翫Ξ繝・ずID';
comment on column DRAFT_KNOWLEDGES.TITLE is '繧ｿ繧､繝医Ν';
comment on column DRAFT_KNOWLEDGES.CONTENT is '蜀・ｮｹ';
comment on column DRAFT_KNOWLEDGES.PUBLIC_FLAG is '蜈ｬ髢句玄蛻・;
comment on column DRAFT_KNOWLEDGES.ACCESSES is '蜈ｬ髢句ｯｾ雎｡';
comment on column DRAFT_KNOWLEDGES.EDITORS is '蜈ｱ蜷檎ｷｨ髮・ｯｾ雎｡';
comment on column DRAFT_KNOWLEDGES.TAG_NAMES is '繧ｿ繧ｰ蜷咲ｧｰ荳隕ｧ';
comment on column DRAFT_KNOWLEDGES.TYPE_ID is '繝・Φ繝励Ξ繝ｼ繝医・遞ｮ鬘曵D';
comment on column DRAFT_KNOWLEDGES.INSERT_USER is '逋ｻ骭ｲ繝ｦ繝ｼ繧ｶ';
comment on column DRAFT_KNOWLEDGES.INSERT_DATETIME is '逋ｻ骭ｲ譌･譎・;
comment on column DRAFT_KNOWLEDGES.UPDATE_USER is '譖ｴ譁ｰ繝ｦ繝ｼ繧ｶ';
comment on column DRAFT_KNOWLEDGES.UPDATE_DATETIME is '譖ｴ譁ｰ譌･譎・;
comment on column DRAFT_KNOWLEDGES.DELETE_FLAG is '蜑企勁繝輔Λ繧ｰ';







