-- 繝励Ο繧ｭ繧ｷ險ｭ螳・
drop table if exists PROXY_CONFIGS cascade;

create table PROXY_CONFIGS (
  SYSTEM_NAME character varying(64) not null
  , PROXY_HOST_NAME character varying(256) not null
  , PROXY_PORT_NO integer not null
  , PROXY_AUTH_TYPE integer not null
  , PROXY_AUTH_USER_ID character varying(256)
  , PROXY_AUTH_PASSWORD character varying(1024)
  , PROXY_AUTH_SALT character varying(1024)
  , PROXY_AUTH_PC_NAME character varying(256)
  , PROXY_AUTH_DOMAIN character varying(256)
  , THIRD_PARTY_CERTIFICATE integer
  , TEST_URL character varying(256)
  , ROW_ID character varying(64)
  , INSERT_USER integer
  , INSERT_DATETIME timestamp
  , UPDATE_USER integer
  , UPDATE_DATETIME timestamp
  , DELETE_FLAG integer
  , constraint PROXY_CONFIGS_PKC primary key (SYSTEM_NAME)
) ;

comment on table PROXY_CONFIGS is '繝励Ο繧ｭ繧ｷ險ｭ螳・;
comment on column PROXY_CONFIGS.SYSTEM_NAME is '繧ｷ繧ｹ繝・Β蜷・;
comment on column PROXY_CONFIGS.PROXY_HOST_NAME is '[Proxy]繝帙せ繝亥錐';
comment on column PROXY_CONFIGS.PROXY_PORT_NO is '[Proxy]繝昴・繝育分蜿ｷ';
comment on column PROXY_CONFIGS.PROXY_AUTH_TYPE is '[Proxy-Auth]隱崎ｨｼ繧ｿ繧､繝・;
comment on column PROXY_CONFIGS.PROXY_AUTH_USER_ID is '[Proxy-Auth]隱崎ｨｼ繝ｦ繝ｼ繧ｶID';
comment on column PROXY_CONFIGS.PROXY_AUTH_PASSWORD is '[Proxy-Auth]隱崎ｨｼ繝代せ繝ｯ繝ｼ繝・;
comment on column PROXY_CONFIGS.PROXY_AUTH_SALT is '[Proxy-Auth]隱崎ｨｼSALT';
comment on column PROXY_CONFIGS.PROXY_AUTH_PC_NAME is '[Proxy-Auth-NTLM]隱崎ｨｼPC蜷・;
comment on column PROXY_CONFIGS.PROXY_AUTH_DOMAIN is '[Auth-NTLM]隱崎ｨｼ繝峨Γ繧､繝ｳ';
comment on column PROXY_CONFIGS.THIRD_PARTY_CERTIFICATE is '[Web]SSL險ｼ譏取嶌繝√ぉ繝・け';
comment on column PROXY_CONFIGS.TEST_URL is '[Web]謗･邯夂｢ｺ隱咲畑URL';
comment on column PROXY_CONFIGS.ROW_ID is '陦栗D';
comment on column PROXY_CONFIGS.INSERT_USER is '逋ｻ骭ｲ繝ｦ繝ｼ繧ｶ';
comment on column PROXY_CONFIGS.INSERT_DATETIME is '逋ｻ骭ｲ譌･譎・;
comment on column PROXY_CONFIGS.UPDATE_USER is '譖ｴ譁ｰ繝ｦ繝ｼ繧ｶ';
comment on column PROXY_CONFIGS.UPDATE_DATETIME is '譖ｴ譁ｰ譌･譎・;
comment on column PROXY_CONFIGS.DELETE_FLAG is '蜑企勁繝輔Λ繧ｰ';








-- 繧ｹ繝医ャ繧ｯ
drop table if exists STOCKS cascade;

create table STOCKS (
  STOCK_ID BIGINT GENERATED BY DEFAULT AS IDENTITY not null
  , STOCK_NAME character varying(256) not null
  , STOCK_TYPE integer not null
  , DESCRIPTION character varying(1024)
  , INSERT_USER integer
  , INSERT_DATETIME timestamp
  , UPDATE_USER integer
  , UPDATE_DATETIME timestamp
  , DELETE_FLAG integer
  , constraint STOCKS_PKC primary key (STOCK_ID)
) ;

-- 繝翫Ξ繝・ず縺ｮ鬆・岼蛟､
drop table if exists KNOWLEDGE_ITEM_VALUES cascade;

create table KNOWLEDGE_ITEM_VALUES (
  KNOWLEDGE_ID bigint not null
  , TYPE_ID integer not null
  , ITEM_NO integer not null
  , ITEM_VALUE text
  , ITEM_STATUS integer not null
  , INSERT_USER integer
  , INSERT_DATETIME timestamp
  , UPDATE_USER integer
  , UPDATE_DATETIME timestamp
  , DELETE_FLAG integer
  , constraint KNOWLEDGE_ITEM_VALUES_PKC primary key (KNOWLEDGE_ID,TYPE_ID,ITEM_NO)
) ;

-- 驕ｸ謚櫁い縺ｮ蛟､
drop table if exists ITEM_CHOICES cascade;

create table ITEM_CHOICES (
  TYPE_ID integer not null
  , ITEM_NO integer not null
  , CHOICE_NO integer not null
  , CHOICE_VALUE character varying(256) not null
  , CHOICE_LABEL character varying(256) not null
  , INSERT_USER integer
  , INSERT_DATETIME timestamp
  , UPDATE_USER integer
  , UPDATE_DATETIME timestamp
  , DELETE_FLAG integer
  , constraint ITEM_CHOICES_PKC primary key (TYPE_ID,ITEM_NO,CHOICE_NO)
) ;

-- 繝・Φ繝励Ξ繝ｼ繝医・繝槭せ繧ｿ
drop table if exists TEMPLATE_MASTERS cascade;

create table TEMPLATE_MASTERS (
  TYPE_ID INT GENERATED BY DEFAULT AS IDENTITY not null
  , TYPE_NAME character varying(256) not null
  , TYPE_ICON character varying(64)
  , DESCRIPTION character varying(1024)
  , INSERT_USER integer
  , INSERT_DATETIME timestamp
  , UPDATE_USER integer
  , UPDATE_DATETIME timestamp
  , DELETE_FLAG integer
  , constraint TEMPLATE_MASTERS_PKC primary key (TYPE_ID)
) ;

-- 繝・Φ繝励Ξ繝ｼ繝医・鬆・岼
drop table if exists TEMPLATE_ITEMS cascade;

create table TEMPLATE_ITEMS (
  TYPE_ID integer not null
  , ITEM_NO integer not null
  , ITEM_NAME character varying(32) not null
  , ITEM_TYPE integer not null
  , INSERT_USER integer
  , INSERT_DATETIME timestamp
  , UPDATE_USER integer
  , UPDATE_DATETIME timestamp
  , DELETE_FLAG integer
  , constraint TEMPLATE_ITEMS_PKC primary key (TYPE_ID,ITEM_NO)
) ;


-- 繧ｹ繝医ャ繧ｯ縺励◆繝翫Ξ繝・ず
drop table if exists STOCK_KNOWLEDGES cascade;

create table STOCK_KNOWLEDGES (
  STOCK_ID bigint not null
  , KNOWLEDGE_ID bigint not null
  , COMMENT character varying(1024)
  , INSERT_USER integer
  , INSERT_DATETIME timestamp
  , UPDATE_USER integer
  , UPDATE_DATETIME timestamp
  , DELETE_FLAG integer
  , constraint STOCK_KNOWLEDGES_PKC primary key (STOCK_ID,KNOWLEDGE_ID)
) ;

comment on table STOCKS is '繧ｹ繝医ャ繧ｯ';
comment on column STOCKS.STOCK_ID is 'STOCK ID';
comment on column STOCKS.STOCK_NAME is 'STOCK 蜷・;
comment on column STOCKS.STOCK_TYPE is '蛹ｺ蛻・;
comment on column STOCKS.DESCRIPTION is '隱ｬ譏・;
comment on column STOCKS.INSERT_USER is '逋ｻ骭ｲ繝ｦ繝ｼ繧ｶ';
comment on column STOCKS.INSERT_DATETIME is '逋ｻ骭ｲ譌･譎・;
comment on column STOCKS.UPDATE_USER is '譖ｴ譁ｰ繝ｦ繝ｼ繧ｶ';
comment on column STOCKS.UPDATE_DATETIME is '譖ｴ譁ｰ譌･譎・;
comment on column STOCKS.DELETE_FLAG is '蜑企勁繝輔Λ繧ｰ';

comment on table KNOWLEDGE_ITEM_VALUES is '繝翫Ξ繝・ず縺ｮ鬆・岼蛟､';
comment on column KNOWLEDGE_ITEM_VALUES.KNOWLEDGE_ID is '繝翫Ξ繝・ずID';
comment on column KNOWLEDGE_ITEM_VALUES.TYPE_ID is '繝・Φ繝励Ξ繝ｼ繝医・遞ｮ鬘曵D';
comment on column KNOWLEDGE_ITEM_VALUES.ITEM_NO is '鬆・岼NO';
comment on column KNOWLEDGE_ITEM_VALUES.ITEM_VALUE is '鬆・岼蛟､';
comment on column KNOWLEDGE_ITEM_VALUES.ITEM_STATUS is '繧ｹ繝・・繧ｿ繧ｹ';
comment on column KNOWLEDGE_ITEM_VALUES.INSERT_USER is '逋ｻ骭ｲ繝ｦ繝ｼ繧ｶ';
comment on column KNOWLEDGE_ITEM_VALUES.INSERT_DATETIME is '逋ｻ骭ｲ譌･譎・;
comment on column KNOWLEDGE_ITEM_VALUES.UPDATE_USER is '譖ｴ譁ｰ繝ｦ繝ｼ繧ｶ';
comment on column KNOWLEDGE_ITEM_VALUES.UPDATE_DATETIME is '譖ｴ譁ｰ譌･譎・;
comment on column KNOWLEDGE_ITEM_VALUES.DELETE_FLAG is '蜑企勁繝輔Λ繧ｰ';

comment on table ITEM_CHOICES is '驕ｸ謚櫁い縺ｮ蛟､';
comment on column ITEM_CHOICES.TYPE_ID is '繝・Φ繝励Ξ繝ｼ繝医・遞ｮ鬘曵D';
comment on column ITEM_CHOICES.ITEM_NO is '鬆・岼NO';
comment on column ITEM_CHOICES.CHOICE_NO is '驕ｸ謚櫁い逡ｪ蜿ｷ';
comment on column ITEM_CHOICES.CHOICE_VALUE is '驕ｸ謚櫁い蛟､';
comment on column ITEM_CHOICES.CHOICE_LABEL is '驕ｸ謚櫁い繝ｩ繝吶Ν';
comment on column ITEM_CHOICES.INSERT_USER is '逋ｻ骭ｲ繝ｦ繝ｼ繧ｶ';
comment on column ITEM_CHOICES.INSERT_DATETIME is '逋ｻ骭ｲ譌･譎・;
comment on column ITEM_CHOICES.UPDATE_USER is '譖ｴ譁ｰ繝ｦ繝ｼ繧ｶ';
comment on column ITEM_CHOICES.UPDATE_DATETIME is '譖ｴ譁ｰ譌･譎・;
comment on column ITEM_CHOICES.DELETE_FLAG is '蜑企勁繝輔Λ繧ｰ';

comment on table TEMPLATE_MASTERS is '繝・Φ繝励Ξ繝ｼ繝医・繝槭せ繧ｿ';
comment on column TEMPLATE_MASTERS.TYPE_ID is '繝・Φ繝励Ξ繝ｼ繝医・遞ｮ鬘曵D';
comment on column TEMPLATE_MASTERS.TYPE_NAME is '繝・Φ繝励Ξ繝ｼ繝亥錐';
comment on column TEMPLATE_MASTERS.TYPE_ICON is '繧｢繧､繧ｳ繝ｳ';
comment on column TEMPLATE_MASTERS.DESCRIPTION is '隱ｬ譏・;
comment on column TEMPLATE_MASTERS.INSERT_USER is '逋ｻ骭ｲ繝ｦ繝ｼ繧ｶ';
comment on column TEMPLATE_MASTERS.INSERT_DATETIME is '逋ｻ骭ｲ譌･譎・;
comment on column TEMPLATE_MASTERS.UPDATE_USER is '譖ｴ譁ｰ繝ｦ繝ｼ繧ｶ';
comment on column TEMPLATE_MASTERS.UPDATE_DATETIME is '譖ｴ譁ｰ譌･譎・;
comment on column TEMPLATE_MASTERS.DELETE_FLAG is '蜑企勁繝輔Λ繧ｰ';

comment on table TEMPLATE_ITEMS is '繝・Φ繝励Ξ繝ｼ繝医・鬆・岼';
comment on column TEMPLATE_ITEMS.TYPE_ID is '繝・Φ繝励Ξ繝ｼ繝医・遞ｮ鬘曵D';
comment on column TEMPLATE_ITEMS.ITEM_NO is '鬆・岼NO';
comment on column TEMPLATE_ITEMS.ITEM_NAME is '鬆・岼蜷・;
comment on column TEMPLATE_ITEMS.ITEM_TYPE is '鬆・岼縺ｮ遞ｮ鬘・;
comment on column TEMPLATE_ITEMS.INSERT_USER is '逋ｻ骭ｲ繝ｦ繝ｼ繧ｶ';
comment on column TEMPLATE_ITEMS.INSERT_DATETIME is '逋ｻ骭ｲ譌･譎・;
comment on column TEMPLATE_ITEMS.UPDATE_USER is '譖ｴ譁ｰ繝ｦ繝ｼ繧ｶ';
comment on column TEMPLATE_ITEMS.UPDATE_DATETIME is '譖ｴ譁ｰ譌･譎・;
comment on column TEMPLATE_ITEMS.DELETE_FLAG is '蜑企勁繝輔Λ繧ｰ';


comment on table STOCK_KNOWLEDGES is '繧ｹ繝医ャ繧ｯ縺励◆繝翫Ξ繝・ず';
comment on column STOCK_KNOWLEDGES.STOCK_ID is 'STOCK ID';
comment on column STOCK_KNOWLEDGES.KNOWLEDGE_ID is '繝翫Ξ繝・ずID';
comment on column STOCK_KNOWLEDGES.COMMENT is '繧ｳ繝｡繝ｳ繝・;
comment on column STOCK_KNOWLEDGES.INSERT_USER is '逋ｻ骭ｲ繝ｦ繝ｼ繧ｶ';
comment on column STOCK_KNOWLEDGES.INSERT_DATETIME is '逋ｻ骭ｲ譌･譎・;
comment on column STOCK_KNOWLEDGES.UPDATE_USER is '譖ｴ譁ｰ繝ｦ繝ｼ繧ｶ';
comment on column STOCK_KNOWLEDGES.UPDATE_DATETIME is '譖ｴ譁ｰ譌･譎・;
comment on column STOCK_KNOWLEDGES.DELETE_FLAG is '蜑企勁繝輔Λ繧ｰ';


ALTER TABLE COMMENTS DROP COLUMN IF EXISTS COMMENT_STATUS;
ALTER TABLE KNOWLEDGES DROP COLUMN IF EXISTS TYPE_ID;
ALTER TABLE COMMENTS ADD COLUMN COMMENT_STATUS integer;
ALTER TABLE KNOWLEDGES ADD COLUMN TYPE_ID integer;

comment on column COMMENTS.COMMENT_STATUS is '繧ｹ繝・・繧ｿ繧ｹ';
comment on column KNOWLEDGES.TYPE_ID is '繝・Φ繝励Ξ繝ｼ繝医・遞ｮ鬘曵D';




DELETE FROM TEMPLATE_MASTERS WHERE TYPE_ID = -100;
DELETE FROM TEMPLATE_ITEMS WHERE TYPE_ID = -100;
DELETE FROM TEMPLATE_MASTERS WHERE TYPE_ID = -99;
DELETE FROM TEMPLATE_ITEMS WHERE TYPE_ID = -99;

INSERT INTO TEMPLATE_MASTERS ( TYPE_ID, TYPE_NAME, TYPE_ICON, DESCRIPTION, INSERT_USER, INSERT_DATETIME, UPDATE_USER, UPDATE_DATETIME, DELETE_FLAG ) 
VALUES 
(-100,'knowledge', 'fa-book', '騾壼ｸｸ縺ｮ繝翫Ξ繝・ず縲りｨｭ螳壹・螟画峩縺ｧ縺阪∪縺帙ｓ縲・,0,'2015-09-09 00:00:00',null,null,0);

INSERT INTO TEMPLATE_MASTERS ( TYPE_ID, TYPE_NAME, TYPE_ICON, DESCRIPTION, INSERT_USER, INSERT_DATETIME, UPDATE_USER, UPDATE_DATETIME, DELETE_FLAG ) 
VALUES 
(-99,'bookmark', 'fa-bookmark', 'Web縺ｫ縺ゅｋ諠・ｱ繧貞・譛峨＠縺ｾ縺吶ら匳骭ｲ縺励◆URL縺ｮ蜀・ｮｹ繧呈､懃ｴ｢蜿ｯ閭ｽ縺ｫ縺励∪縺吶りｨｭ螳壹・螟画峩縺ｧ縺阪∪縺帙ｓ縲ゑｼ育屮逅・・・Proxy縺ｮ險ｭ螳壹ｒ陦後▲縺ｦ縺上□縺輔＞・・,0,'2015-09-09 00:00:00',null,null,0);

INSERT INTO TEMPLATE_ITEMS ( TYPE_ID, ITEM_NO, ITEM_NAME, ITEM_TYPE, INSERT_USER, INSERT_DATETIME, UPDATE_USER, UPDATE_DATETIME, DELETE_FLAG ) 
VALUES 
(-99,0,'URL',0,0,'2015-09-09 00:00:00',null,null,0);

UPDATE KNOWLEDGES SET TYPE_ID = -100;
